name: Automatic testing
on: [push]
jobs:
  Run-All-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install pytest
      - name: Run pytest
        run: pytest
